#!/usr/bin/env bash
# Reads /opt/pocketbase/projects.conf and generates:
#   - /etc/systemd/system/pocketbase-<name>.service  (one per project)
#   - /etc/caddy/sites/pocketbase.conf               (project subdomains)
# Then reloads systemd + Caddy.
#
# Caddy sites live in /etc/caddy/sites/*.conf, IMPORTED by the main Caddyfile,
# so this script NEVER touches other sites (e.g. locket.atensai.com).
#
# Run as root after editing projects.conf.
set -euo pipefail

PB_HOME="/opt/pocketbase"
CONF="${1:-$PB_HOME/projects.conf}"
SYSTEMD_DIR="/etc/systemd/system"
CADDY_DIR="/etc/caddy"
SITES_DIR="$CADDY_DIR/sites"
PB_SITES="$SITES_DIR/pocketbase.conf"
CADDYFILE="$CADDY_DIR/Caddyfile"

[ -f "$CONF" ] || { echo "Missing $CONF"; exit 1; }
mkdir -p "$SITES_DIR"

rm -f "$SYSTEMD_DIR"/pocketbase-*.service

# Collect projects: skip blank lines and comments
grep -Ev '^\s*(#|$)' "$CONF" | while read -r name port domain; do
  [ -n "$name" ] || continue

  unit="$SYSTEMD_DIR/pocketbase-$name.service"
  cat > "$unit" <<EOF
[Unit]
Description=PocketBase instance: $name
After=network.target

[Service]
Type=simple
User=pocketbase
Group=pocketbase
WorkingDirectory=$PB_HOME/$name
ExecStart=$PB_HOME/pocketbase serve \\
  --http=127.0.0.1:$port \\
  --dir=$PB_HOME/$name/data \\
  --migrationsDir=$PB_HOME/$name/pb_migrations \\
  --hooksDir=$PB_HOME/$name/pb_hooks \\
  --publicDir=$PB_HOME/$name/pb_public
Restart=on-failure
RestartSec=5
# Set a real secret (32+ chars) — encrypts sensitive records in SQLite
Environment=PB_ENCRYPT_KEY=CHANGE_ME_to_a_long_random_string

[Install]
WantedBy=multi-user.target
EOF

  echo "  wrote $unit ($domain -> :$port)"
done

# Regenerate the PocketBase sites file (the main Caddyfile imports it)
{
  echo "# PocketBase project sites — generated by generate.sh (do not edit)"
  grep -Ev '^\s*(#|$)' "$CONF" | while read -r name port domain; do
    [ -n "$name" ] || continue
    cat <<EOF

$domain {
	encode zstd gzip
	reverse_proxy 127.0.0.1:$port
}
EOF
  done
} > "$PB_SITES"

# Make sure the main Caddyfile imports the sites dir (idempotent)
if ! grep -q "import $SITES_DIR/" "$CADDYFILE" 2>/dev/null; then
  { echo "import $SITES_DIR/*.conf"; echo; cat "$CADDYFILE" 2>/dev/null || true; } > "$CADDYFILE.new"
  mv "$CADDYFILE.new" "$CADDYFILE"
  echo "  added 'import $SITES_DIR/*.conf' to $CADDYFILE"
fi

systemctl daemon-reload
# Caddy is optional — without it the project still runs (on its port), just
# without an https subdomain. Don't fail the whole run if it's not present.
systemctl reload caddy 2>/dev/null || echo "  (caddy not running — reload skipped)"

echo ""
echo "Done. For each new project:"
echo "  mkdir -p $PB_HOME/<name>"
echo "  systemctl enable --now pocketbase-<name>"
echo "  # then open https://<domain>/_/ to create the admin"
